import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    fontFamily: '"Geist", "Inter", sans-serif',
    maxWidth: '420px',
    margin: '0 auto',
    background: 'rgba(255, 255, 255, 0.95)',
    borderRadius: '24px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.15), 0 0 0 1px rgba(0,0,0,0.02)',
    padding: '32px',
    position: 'relative',
    overflow: 'hidden',
    backdropFilter: 'blur(10px)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '40px',
  },
  logoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  logoIcon: {
    width: '24px',
    height: '24px',
    background: '#111',
    color: '#fff',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    fontSize: '14px',
  },
  logoText: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#111',
    letterSpacing: '-0.5px',
  },
  walletBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 12px',
    background: '#f3f4f6',
    borderRadius: '20px',
  },
  walletAvatar: {
    width: '16px',
    height: '16px',
    borderRadius: '50%',
  },
  walletAddress: {
    fontSize: '12px',
    fontWeight: '500',
    color: '#4b5563',
    fontFamily: 'monospace',
  },
  disconnectedBadge: {
    fontSize: '12px',
    color: '#ef4444',
    background: '#fef2f2',
    padding: '4px 10px',
    borderRadius: '20px',
    fontWeight: '600',
  },
  amountSection: {
    marginBottom: '40px',
    textAlign: 'center',
  },
  label: {
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    color: '#9ca3af',
    fontWeight: '600',
    marginBottom: '12px',
    display: 'block',
  },
  hugeDisplay: {
    fontSize: '48px',
    fontWeight: '700',
    color: '#111',
    letterSpacing: '-2px',
  },
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'baseline',
  },
  currencyPrefix: {
    fontSize: '32px',
    color: '#d1d5db',
    fontWeight: '500',
    marginRight: '4px',
  },
  hugeInput: {
    fontSize: '56px',
    fontWeight: '700',
    color: '#111',
    border: 'none',
    background: 'transparent',
    textAlign: 'center',
    width: '240px',
    letterSpacing: '-2px',
    outline: 'none',
  },
  currencySymbol: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#9ca3af',
    marginLeft: '8px',
  },
  actionSection: {
    marginTop: 'auto',
  },
  networkInfo: {
    textAlign: 'center',
    fontSize: '12px',
    color: '#6b7280',
    marginBottom: '16px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '6px',
  },
  networkDot: {
    width: '6px',
    height: '6px',
    background: '#10b981',
    borderRadius: '50%',
    boxShadow: '0 0 0 2px rgba(16, 185, 129, 0.2)',
  },
  payButton: {
    width: '100%',
    height: '56px',
    background: '#111',
    color: '#fff',
    border: 'none',
    borderRadius: '16px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  payButtonDisabled: {
    background: '#e5e7eb',
    color: '#9ca3af',
    cursor: 'not-allowed',
  },
  loadingSpinner: {
    width: '20px',
    height: '20px',
    border: '2px solid rgba(255,255,255,0.3)',
    borderTopColor: '#fff',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  stepperContainer: {
    background: '#f9fafb',
    borderRadius: '16px',
    padding: '24px',
    marginBottom: '24px',
  },
  stepperTrack: {
    display: 'flex',
    justifyContent: 'space-between',
    position: 'relative',
    marginBottom: '16px',
  },
  stepItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    zIndex: 1,
    position: 'relative',
  },
  stepDot: {
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    background: '#fff',
    border: '2px solid #e5e7eb',
    marginBottom: '8px',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotActive: {
    borderColor: '#3b82f6',
    boxShadow: '0 0 0 4px rgba(59, 130, 246, 0.1)',
  },
  stepDotCompleted: {
    background: '#3b82f6',
    borderColor: '#3b82f6',
    color: '#fff',
  },
  stepLabel: {
    fontSize: '10px',
    fontWeight: '600',
    color: '#9ca3af',
    textTransform: 'uppercase',
  },
  stepLabelActive: {
    color: '#3b82f6',
  },
  checkmark: {
    fontSize: '12px',
    fontWeight: 'bold',
  },
  stepMessage: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#4b5563',
    fontWeight: '500',
  },
  errorBox: {
    background: '#fef2f2',
    color: '#dc2626',
    padding: '16px',
    borderRadius: '12px',
    fontSize: '13px',
    marginBottom: '24px',
    textAlign: 'center',
  },
  successBox: {
    background: '#f0fdf4',
    color: '#16a34a',
    padding: '16px',
    borderRadius: '12px',
    fontSize: '13px',
    marginBottom: '24px',
    textAlign: 'center',
  },
  link: {
    color: '#16a34a',
    fontWeight: '700',
    marginLeft: '6px',
    textDecoration: 'underline',
  },
  stepDotSpinner: {
    width: '14px',
    height: '14px',
    border: '2px solid rgba(59, 130, 246, 0.2)',
    borderTopColor: '#3b82f6',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
};
